language: csharp
dist: trusty
mono: none
dotnet: 2.1.4
script:
- dotnet restore src
- dotnet build -c release src/PageUp.CldrPackager/PageUp.CldrPackager.csproj
- dotnet pack -c release src/PageUp.CldrPackager/PageUp.CldrPackager.csproj
