version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    dotnet build -c release src/PageUp.CldrPackager/PageUp.CldrPackager.csproj

    dotnet test src/PageUp.CldrPackager.Test/PageUp.CldrPackager.Test.csproj

    dotnet pack -c release src/PageUp.CldrPackager/PageUp.CldrPackager.csproj  /p:Version=%APPVEYOR_BUILD_VERSION% 

artifacts: 
  - path: ./src/PageUp.CldrPackager/bin/release/*.nupkg
  
deploy:
  on:
    branch: master
  provider: NuGet
  api_key:
    secure: Q9tkLQmKthhGcrD7gUr4JnpJOkQpbop3gtsuw0ZKMWDwnr+z//aR8gA4fg1aX1in
  skip_symbols: false 
