version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    dotnet build -c release src/PageUp.CldrPackager/PageUp.CldrPackager.csproj

    dotnet test src/PageUp.CldrPackager.Test/PageUp.CldrPackager.Test.csproj

    dotnet pack -c release src/PageUp.CldrPackager/PageUp.CldrPackager.csproj  /p:Version=%APPVEYOR_BUILD_VERSION% 

artifacts: 
  - path: ./src/PageUp.CldrPackager/bin/release/*.nupkg
  
deploy:
  on:
    branch: master
  provider: NuGet
  api_key:
    secure: L2dEfmo+IaWNLRp0+b4BLklU2kqvvvAy1i5SC9693OWhbxtWNA3rVQ8Ly3xqdtCX
  skip_symbols: false 
